CREATE TABLE if not exists zones (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name TEXT
);

CREATE TABLE if not exists routes (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          zone_id int,
                          name TEXT,
                          description TEXT,
                          length_hours float
);

CREATE TABLE if not exists feature_types (
                                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name TEXT
);

CREATE TABLE if not exists route_features (
                                  route_id int,
                                  feature_id int,
                                  PRIMARY KEY (route_id, feature_id)
);

CREATE TABLE if not exists visit_permits (
                                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 status int,
                                 requested_at timestamp without time zone,
                                 route_id int,
                                 visit_date date,
                                 group_id int,
                                 visit_reason int,
                                 visit_format int,
                                 photo_type int,
                                 first_name TEXT,
                                 last_name TEXT,
                                 middle_name TEXT,
                                 citizenship TEXT,
                                 registration_region TEXT,
                                 is_male boolean,
                                 passport TEXT,
                                 email TEXT,
                                 phone TEXT
);

CREATE TABLE if not exists permit_statuses (
                                   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name TEXT
);

CREATE TABLE if not exists visit_reasons (
                                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name TEXT
);

CREATE TABLE if not exists photo_types (
                               id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name TEXT
);

CREATE TABLE if not exists visit_format (
                                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name TEXT
);

CREATE TABLE if not exists group_permits (
                                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE if not exists reports (
                           id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           sent_at date,
                           reported_at timestamp without time zone,
                           location TEXT,
                           type TEXT,
                           photo bytea,
                           comment TEXT,
                           name TEXT,
                           email TEXT,
                           phone TEXT
);

ALTER TABLE routes ADD FOREIGN KEY (zone_id) REFERENCES zones (id);
ALTER TABLE route_features ADD FOREIGN KEY (route_id) REFERENCES feature_types (id);
ALTER TABLE route_features ADD FOREIGN KEY (feature_id) REFERENCES routes (id);
ALTER TABLE visit_permits ADD FOREIGN KEY (status) REFERENCES permit_statuses (id);
ALTER TABLE visit_permits ADD FOREIGN KEY (route_id) REFERENCES routes (id);
ALTER TABLE visit_permits ADD FOREIGN KEY (group_id) REFERENCES group_permits (id);
ALTER TABLE visit_permits ADD FOREIGN KEY (visit_reason) REFERENCES visit_reasons (id);
ALTER TABLE visit_permits ADD FOREIGN KEY (visit_format) REFERENCES visit_format (id);
ALTER TABLE visit_permits ADD FOREIGN KEY (photo_type) REFERENCES photo_types (id);

-- TODO: hardcode fields